[package]
name = "raylib-sys"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.37.4"
